
# all stickers ids from the pack: omgitiscooleststickersintheworld
stickers_id = [
                'CAACAgIAAxkBAAOlYpEyya8DqvsRHkS9-jVEJNuRIg0AAlgQAAK5U8lKH-A6HtDU-KgkBA',
                'CAACAgIAAxkBAAOoYpEy5kcKeXF1TXpmU_oBQA6ETZYAAjkPAAL2ccFK31u-sV-49M8kBA',
                'CAACAgIAAxUAAWKRMZZFousVftjEshqumRj57Vo_AALdDgACENrJSjuCt_dsyJ_4JAQ',
                'CAACAgIAAxUAAWKRMZZlazaHwFxNRWiwpczFetiQAALxDQAC2LnJSlh5waL4QdGzJAQ',
                'CAACAgIAAxUAAWKRMZYYSdcYVPaItbYIWL9pKOMNAAIfEAACQtfASggTvZxmWOiOJAQ',
                'CAACAgIAAxUAAWKRMZbJ5atJ0iHfqNITSCNyBXEeAAL6DgACI9XRSgABzO3UDVswQSQE',
                'CAACAgIAAxUAAWKRMZZp3YNbDn6HzkyyOsE4SDF2AAJaDAACxbLxSr6umFdHWOAEJAQ',
                'CAACAgIAAxUAAWKRMZab4j_BefTsHmahoFxc-qX0AAK2DgACjUEBS9vsrUpWaoC0JAQ',
                'CAACAgIAAxUAAWKRMZa-CakPBiQSIWACQsXERzezAAJTDgACeof4SrbwCcAaXROOJAQ',
                'CAACAgIAAxUAAWKRMZYPsxtL4bgcU3qmeWtJ8Gb_AALRDwACm4UAAUsS1kTHCb_BaSQE',
                'CAACAgIAAxUAAWKRMZbGDiJDDwi8mzQf8CpqXVAEAAKbDQACbfkBS4PikqTH0b-NJAQ',
                'CAACAgIAAxUAAWKRMZaBgBdqiiinxPHHL2MyR57yAALWDwAC3i0BS7Ji2mFgnolWJAQ',
                'CAACAgIAAxUAAWKRMZaRwGVZmcz6JjdbbohMgGSLAAL_EQACiksIS4mH_RyIRK4TJAQ',
                'CAACAgIAAxUAAWKRMZafnDtqJg8QNnGCFQHMSoTCAAJFDwACGQcAAUuuKQl2sRdfgyQE',
                'CAACAgIAAxUAAWKRMZZCGVXtsaZm2FYlOaEtWG0fAAKKDQACj5YRS6E24E4-86zCJAQ',
                'CAACAgIAAxUAAWKRMZZ9yFa6IjPIqr_saFuRd9n6AAI5DwACVwwRS5XKyJXNSxBhJAQ',
                'CAACAgIAAxUAAWKRMZYg3TBck1Iw1KWOidlcmvndAAIlDgACUboISxKzjdjhXon7JAQ',
                'CAACAgIAAxUAAWKRMZbKQ7PN5PeYIS3pYSsEAqmzAAJDDgACxQABGEtsWkW8tHHcESQE',
                'CAACAgIAAxUAAWKRMZaut1nh3V2f7AZRmJrU1ix9AAKzDQACPTEgS7oEXgIZbj8lJAQ',
                'CAACAgIAAxUAAWKRMZYRLTTRuXXuit9XavinWXouAAL1EAACS3QgS3uphsk1j_e5JAQ',
                'CAACAgIAAxUAAWKRMZZ6pfEMftEXHQRnQUmXwE1OAAJgDwACtEUoS1cW-ZNW_NTrJAQ',
                'CAACAgIAAxUAAWKRMZZV6khRazXhTOiZf-nWZGJ-AAJNDgACCecgSxZfSSy--JVTJAQ',
                'CAACAgIAAxUAAWKRMZZd3rUkPjufQKgFjdgkRMKbAALoDgACXKYgS4AgH6-90zS-JAQ',
                'CAACAgIAAxUAAWKRMZalSSziMmaT0lw26MpqHhwbAAJnDwACvvghS6xAxLkPAAErdSQE',
                'CAACAgIAAxUAAWKRMZazusIjYp1wwl89qNJ4_Wm-AAJmDwACtRAoS3MJJeI3raFSJAQ',
                'CAACAgIAAxUAAWKRMZY4-ewKFcnI-_15TLXImZqyAAKkEgACIuooSyB7a3kf-lPMJAQ',
                'CAACAgIAAxUAAWKRMZYa8lhXytWC27w5iGKdr01yAAKLDgACOU8hS6WHN53reQcLJAQ',
                'CAACAgIAAxUAAWKRMZYCjr3nncjO5QmN6mtGN5D5AAKQEAACBUwpS-pBsfWvfdDcJAQ',
                'CAACAgIAAxUAAWKRMZYO2Wf0OOOl7dncNLS4YYxpAAJWEgACpGwhSw5KOaVFV41PJAQ',
                'CAACAgIAAxUAAWKRMZb2eX-k8jhC5E9ejRspd37vAAL6EAACCN0pS00YQGa0H2IDJAQ',
                'CAACAgIAAxUAAWKRMZZLXLoKO29mtmF21W8t_IFWAAKzEAACucYgS_CHpziFCoVKJAQ',
                'CAACAgIAAxUAAWKRMZaYHtNK_QgzZnqinf8UpOXDAAJVEAACt24gS_0xqLu9NEOuJAQ',
                'CAACAgIAAxUAAWKRMZaKUN2pPKoeu_u8hfSAfQABHAACNg4AAr60QEtvflpXYf9ceyQE',
                'CAACAgIAAxUAAWKRMZaifJ5sFpAZhhvO1m_XU4sgAALnDwAC4RRBS4M8PS33U1VDJAQ',
                'CAACAgIAAxUAAWKRMZZMuFx2aN7bOXceMn_gnbvFAAKLEgAC15pZSKMbNLKT2X-lJAQ',
                'CAACAgIAAxUAAWKRMZb0poGJ1XznD9VXBjSm8-l1AALnEAAC2-pZSLldd3KMhTdmJAQ',
                'CAACAgIAAxUAAWKRMZa0k_gG2Blwo1b6yI6rRQo7AAJnEQAC5rNYSN_C5jYsxKxwJAQ',
                'CAACAgIAAxUAAWKRMZYS7mzlnhkpsDdNl8DwXLTuAAJaEQACmmjYSEf-nwi1ItUpJAQ',
                'CAACAgIAAxUAAWKRMZYBtxClgRCCbrbEkIEiZuriAALKEAAC18vRSDLs57qZqeBeJAQ',
                'CAACAgIAAxUAAWKRMZb96IHp3xyI-7ScbCcUuiIAA6ISAAIBXflIDy2EgR9J89kkBA',
                'CAACAgIAAxUAAWKRMZaVm8Q0QgZgRMPOIzNFKRuYAAI5DgACwmtRSlCii-REMUuvJAQ',
                'CAACAgIAAxUAAWKRMZbJuPQOkX5oFclDg8Xsy1T8AAL6DwACgmhoStVUCUYN-5I8JAQ',
                'CAACAgIAAxUAAWKRMZZbQhRN0z6gVpk3G55ZaE_7AAJyDQACLI1xStaVVMdQEWhsJAQ',
                'CAACAgIAAxUAAWKRMZa70ASr97xXDuRxEpsV29uwAALaEAAC5niQSgPvbIeoQ3ChJAQ',
                'CAACAgIAAxUAAWKRMZZ6jKBBqXejIdsBNt4Zs1X0AALTEQACvd6QSlQMRAay4ZTPJAQ',
                'CAACAgIAAxUAAWKRMZaB23awxIsAAbT8i81kURBYpAACaRgAAtDFkEpoWtgUUSgMtyQE',
                'CAACAgIAAxUAAWKRMZZtuEHDY4pVyLlhf2ZevgnZAALoFQAC7laQSrkv3h1I3WO1JAQ',
                'CAACAgIAAxUAAWKRMZYdeXGDM6WB6c4uIQ9f-60UAAKjDgACJnbYS3XQ8AQAAXuPICQE',
                'CAACAgIAAxUAAWKRMZaevJS8wB3OVtVdY2u6iNM4AALHDQAC7HnRSxPIx8GPl0fdJAQ',
                'CAACAgIAAxUAAWKRMZbMWudStwvT67IUhljtqaXfAAIyFAACR6mwSKNzBK6LNBGxJAQ',
                'CAACAgIAAxUAAWKRMZa6pgm2Id4q0hy_fD0azkFUAAJhFAACK7-4SOOfcJ4DVu6OJAQ',
                'CAACAgIAAxUAAWKRMZbI6HUe432qJn4p0MmksXfVAAIhFQACu4R4S6iAjCmOK5kMJAQ',
                'CAACAgIAAxUAAWKRMZYIrH58QccJDRVXnVeVX2yPAAIYEwACpyt5S-8_af3ILHV7JAQ',
                'CAACAgIAAxUAAWKRMZa9xtvh801ZumldSWPhK5aoAAJ8FAAC44moS3nx_WJLzOT-JAQ',
                'CAACAgIAAxUAAWKRMZb2VSevfftoj0FewoGKa0bcAAL6GwAC1RzwSXekA02CzNrkJAQ',
                'CAACAgIAAxUAAWKRMZZjbYXbBIwXC3EWZbdKIGHZAAIFEwACFQ3oScuhP1Mun1MOJAQ',
                'CAACAgIAAxUAAWKRMZZp3Zr7-PzwE_N8_4nvP2qpAAKIGAACJW0JSoVlrKRWePxaJAQ',
                'CAACAgIAAxUAAWKRMZYeFUORDeA30rR4IGdkjHftAAJiGAACfeQRSr41c5qn6bGGJAQ',
                'CAACAgIAAxUAAWKRMZZY9VMXCr4VaicveBGDNG51AAI0GAACVr0ZShX-Fojo87KgJAQ',
                'CAACAgIAAxUAAWKRMZZ0FEnGJ80EobCdH94hyfMRAAKAFgAC4T6wSkIDrvBmTYv2JAQ',
                'CAACAgIAAxUAAWKRMZbVlRCNVZ0yOBuTNwxKOYzGAALtHwAC_7QAAUvgztrvjN0iECQE',
                'CAACAgIAAxUAAWKRMZa35Q3f2PUXdBEPBcrSzaISAAIrGAACySYBS9cIwgUWqPPaJAQ'
                ]

# https://redburda.ru/segodnya-stavish-vpn-a-zavtra-nato-sdashsya-v-plen/
today_reply = [
    "СЕГОДНЯ СТАВИШЬ VPN, А ЗАВТРА НАТО СДАШЬСЯ В ПЛЕН!",
    "Сегодня борешься за мир, А завтра – сзади конвоир.",
    "Сегодня стал ты пацифистом, А завтра – падлой и нацистом!",
    "Сегодня гнусная мразота, А завтра – мразь и либеро́та!",
    "Сегодня крикнул: «Нет войне!», А завтра  – изменил жене!",
    "Сегодня постишь вражьи фейки, А завтра – сдохнешь без копейки!",
    "Сегодня ты экономист, А завтра гад и экстремист!",
    "Сегодня твой кумир Навальный, А завтра – с шваброю ректальной!",
    "Сегодня хочешь ты в Париж, А завтра хрен тебе и шиш!",
    "Сегодня доллар шестьдесят, А завтра двести шестьдесят!",
    "Сегодня ты на БМВ, А завтра – «Лада» с Z и V!",
    "Сегодня ты читаешь Пруста, А завтра – лапти, щи, капуста!",
    "Сегодня ты читаешь книжки, А завтра будешь умный слишком!",
    "Сегодня пляшешь на эстраде, А завтра просишь Христа ради!",
    "Сегодня спел «Червону руту», А завтра в Тынду по маршруту!",
    "К евреям воспылал любовью? Ты Гитлер-жид с еврейской кровью!",
    "Сегодня сел за диссертацию, А завтра – за дискредитацию!",
    "Сегодня пишешь «мирумир», А завтра будешь пить чифир!",
    "Вчера копил ты на «Рено», Теперь «Рено» смотри в кино!",
    "Сегодня перепостил ссылку, А завтра сядешь на бутылку!",
    "Вчера смеялся над гарантом, Сегодня станешь фигурантом!",
    "Сегодня смотришь ты Чулпан? Вокзал, Европа, чемодан!",
    "Сегодня пишешь о ГУЛАГе, А завтра на скамье в Гааге!"
]
